### ISSUE TITLE
Cater for more than 2 away talks

### ISSUE THREAD

**Issue by fstouma** [ajtruckle/meeting-schedule-assistant-support#1]
At the moment Meeting Schedule Assistant can only cater for a maximum of **2 away talks** on the [Weekend Meeting Editor](https://help-msa.publictalksoftware.co.uk/mwb-editor-weekend-meeting.html) window:

![AwayTalks](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/36dfeea8-c473-417f-bbf1-f54e237838f3)

In the [Public Talks](https://help-pts.publictalksoftware.co.uk/pts-editing-home-talk-entries.html) application is does not have this limitation:

![PublicTalks-AwayTalks](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/4ae997b5-fc56-4d2f-a8d2-a9365a1d5805)

It would be great if Meeting Schedule Assistant could do the same.

**Comment by ajtruckle** [comment]
@fstouma Let me think about the best way to address this feature request. 🤔 I'll update you in due course.

**Comment by ajtruckle** [comment]
@fstouma The good news is that the structure of XML data used by the Meeting Editor can already cope with any number of away talks. 😊

###  XML ###
```
<AwayTalk>
    <Speaker>Name</Speaker>
    <Congregation>Congregation</Congregation>
    <ThemeNumber>158</ThemeNumber>
    <MeetingDate Day="12" DayShort="Sun" DayFull="Sunday" Month="11" MonthShort="Nov" MonthFull="November" Year="2023">12/11/2023</MeetingDate>
    <MeetingTime Time12="10:00" Time24="10:00"/>
</AwayTalk>
```

### XSL ###

```
<xsl:apply-templates select="AwayTalk"/>
```
So the schedule would still display all away talks by design without needed any changes to the XML data or XSL templates.

Required Changes
---
Several areas need to be changed though:

- Assignment History Database
- User Interface (Weekend Meeting Editor)
- User Interface (Weekend Meeting Editor - Import from Public Talks)
- Calendar Synchronization

**Comment by ajtruckle** [comment]
@fstouma 
Part of the problem is the design of the GUI. In **Public Talks** it is designed like this:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/03ea9818-983f-458c-8b59-7112c80915ed)

But, in **Meeting Schedule Assistant** we have less real-estate (it is not as wide:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/64380a77-0d1a-40ce-accb-d8f31624c195)
I am open to suggestions💡from yourself or anyone else about changing the GUI to make this work.

**Comment by fstouma** [comment]
Just wondering, can it be a form that enables the user to add one talk at a time and you can view them by a report?

**Comment by ajtruckle** [comment]
Hi @fstouma, thanks for the suggestion. I now have an idea💡formulating in my mind.👍

**Comment by ajtruckle** [comment]
@fstouma @mardodan

This is my proposal:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/983a6492-2c9a-41c3-8f63-72a91fae4653)

We move the **Video Operator** control over to the right to give us more real-estate. Now we have more room for the new controls. They are similar to the _Public Talks_ GUI (without the **Tentative** column). This would work.

**Comment by ajtruckle** [comment]
@fstouma @mardodan

Like this:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/75ef5949-a250-44d5-98b7-c96b77731e76)

Work in progress!

**Comment by ajtruckle** [comment]
@fstouma @mardodan

I have made some progress:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/078e56cf-b0ee-4b44-973f-d4c57ca7b081)

But there is quite a bit of work to do before I can issue a beta.

**Comment by ajtruckle** [comment]
@fstouma @MardoDan

I didn't really how much that this change to the Away Talks feature would impact the application. I am now knee deep in implementation! But there are some other areas that I still need to revise for this to work properly.

**Comment by ajtruckle** [comment]
https://stackoverflow.com/q/77242954/2287576

**Comment by ajtruckle** [comment]
@MardoDan @stecchio66

The **Import** (from Public Talks) window has been updated to support more than two away talks:

![image](https://github.com/ajtruckle/meeting-schedule-assistant-support/assets/7985331/68f4634e-b90c-4902-ab74-ee7b2ef6a7f7)

**Comment by MardoDan** [comment]
Excelente Trabajo!!!

**Comment by ajtruckle** [comment]
@MardoDan Thank you! 😊

I have now completed all required changes to the software for this feature request.

> **Note**
> I still need to revise 👀 all the **help documentation**. But I would like beta feedback 💬 in the first instance. I sent you a download link (privately) to beta number 5 earlier today.

**Comment by MardoDan** [comment]
Excelente trabajo, hasta ahora no le encontré errores. Se pueden agregar mas de dos salidas de discursantes

**Comment by ajtruckle** [comment]
> [!NOTE]  
>  The [online newsletter](https://www.publictalksoftware.co.uk/2023/10/msa-version-24-1-1-news/) for version **24.1.1** is now available.
