### ISSUE TITLE
Report Viewer menu location

### ISSUE THREAD

**Issue by cengizu** [ajtruckle/meeting-schedule-assistant-support#104]
**Is your feature request related to a problem? Please describe.**
There seem to be two menu paths to access the Report Viewer in its current operation: 

1. Menu > Database > Congregations > Report Viewer
2. Menu > Database > Public Talks > Report Viewer

**Describe the solution you'd like**
A single menu entry for Report Viewer would be good.

For ex.
![MSA-Report_Viewer](https://github.com/user-attachments/assets/451781b8-8054-4cdb-97cd-1b58cc97ba78)

**Comment by ajtruckle** [comment]
@cengizu 
I agree that we need to simplify the menu navigation. In fact, there is a third place:

3. Publishers Database > Database Menu > Report Viewer

Here are my thoughts 🤔:

The Report Viewer is useful for the following parts of the software:

* Congregations
* Foreign Language Groups
* Publishers
* Public Talks

I think it would be useful for all of these windows to have direct access to the Report Viewer too, either via a menu or a button. I am open to suggestions. Otherwise, you have to close the dialogs to gain access to the viewer.

Also, the main toolbar has direct access to the Congregations report viewer mode. I guess it makes sense to keep this arrangement.

**Comment by ajtruckle** [comment]
@cengizu 
I am setting you a new beta with the agreed improvements.

>[!Note]
> I still need to update the translations and add the menu item bitmaps
